### ISSUE TITLE
rmba.R seems not work

### ISSUE THREAD

**Issue by HattieLIN** [johnjdavisiv/rmba#1]
Hi, I'm very interested in this code. However, I can't find the "rmba.R". Could you provide some guidance? Thanks a lot!
> source("rmba.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'rmba.R': No such file or directory

**Comment by johnjdavisiv** [comment]
Make sure you set your path to include the folder where you downloaded the repository. In RStudio if you have the example file open you can go to the menu bar and click Session > Set Working Directory > To Source File Location. Make sure you downloaded the whole repository, too, not just the example file!
